sudo: required

language: c++
compiler: g++
git:
  submodules: false

install:
  - chmod +x install-protobuf.sh && ./install-protobuf.sh

script: 
  - chmod +x configure && ./configure --prefix=/usr && make -j2 && sudo make install

notifications:
  email: true
    #recipients:
    # - ******@***.com
    #on_success: [always|never|change]  default: change
    #on_failure: [always|never|change]  default: always